<?php
return array(
	'delete' => true,
	'delete_log' => 'Usunięto podstronę: %s',
	'delete_log_sub' => 'title',
	'add_log' => 'Dodano podstronę: %s',
	'add_log_sub' => 'title',
	'edit_log' => 'Zmieniono podstronę: %s',
	'edit_log_sub' => 'title',
	'table' => 'pages',
	'edit' => true,
	'create' => true,
	'acl_delete' => 'admin_page_delete',
	'acl_edit' => 'admin_page_edit',
	'acl_add' => 'admin_page_add',
	'title' => 'Podstrony',
	'title_edit' => 'Edycja podstrony',
	'title_add' => 'Dodawanie podstrony',
	'slug' => 'slug',
	'slug_from' => 'title',
	'grid' => true,
	'acl_grid' => 'admin_page',
	'acl_grid_multi' => 'admin_page_multi',
	'fields_create' => array(
		'Podstawowe' => array(
			'title' => array(
				'label' => 'Tytuł',
				'description' => 'Tytuł podstrony',
				'type' => 'text',
				'validators' => 'required|max:127|unique:pages,title',
				'escape' => true,
			),
			'page_content' => array(
				'label' => 'Zawartość',
				'description' => 'Zawartość podstrony',
				'type' => 'editor',
				'validators' => 'required',
			),
		),
		'SEO' => array(
			'meta_title' => array(
				'label' => 'META title',
				'description' => 'Zawartość tagu title. Domyślnie tytuł strony',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'meta_keys' => array(
				'label' => 'META keywords',
				'description' => 'Zawartość meta tagu keywords',
				'type' => 'textarea',
				'validators' => 'max:255',
				'escape' => true,
			),
			'meta_description' => array(
				'label' => 'META description',
				'description' => 'Zawartość meta tagu description',
				'type' => 'textarea',
				'validators' => 'max:255',
				'escape' => true,
			),
		),
	),
	'fields_edit' => array(
		'Podstawowe' => array(
			'title' => array(
				'label' => 'Tytuł',
				'description' => 'Tytuł podstrony',
				'type' => 'text',
				'validators' => 'required|max:127|unique:pages,title,(:id)',
				'escape' => true,
			),
			'slug' => array(
				'label' => 'Slug',
				'description' => 'Slug widoczny w linkach do podstrony',
				'type' => 'text',
				'validators' => 'required|max:127|alpha_dash|unique:pages,slug,(:id)',
				'escape' => true,
			),
			'page_content' => array(
				'label' => 'Zawartość',
				'description' => 'Zawartość podstrony',
				'type' => 'editor',
				'validators' => 'required',
			),
		),
		'SEO' => array(
			'meta_title' => array(
				'label' => 'META title',
				'description' => 'Zawartość tagu title. Domyślnie tytuł strony',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'meta_keys' => array(
				'label' => 'META keywords',
				'description' => 'Zawartość meta tagu keywords',
				'type' => 'textarea',
				'validators' => 'max:255',
				'escape' => true,
			),
			'meta_description' => array(
				'label' => 'META description',
				'description' => 'Zawartość meta tagu description',
				'type' => 'textarea',
				'validators' => 'max:255',
				'escape' => true,
			),
		),
	),
);