<?php
return array(
	'delete' => true,
	'delete_log' => 'Usunięto zawodnika: %s',
	'delete_log_sub' => 'name',
	'add_log' => 'Dodano zawodnika: %s',
	'add_log_sub' => 'name',
	'edit_log' => 'Zmieniono zawodnika: %s',
	'edit_log_sub' => 'name',
	'table' => 'players',
	'edit' => true,
	'create' => true,
	'acl_delete' => 'admin_players_delete',
	'acl_edit' => 'admin_players_edit',
	'acl_add' => 'admin_players_add',
	'title' => 'Zawodnicy',
	'title_edit' => 'Edycja zawodnika',
	'title_add' => 'Dodawanie zawodnika',
	'slug' => 'slug',
	'slug_from' => 'name',
	'grid' => true,
	'acl_grid' => 'admin_players',
	'acl_grid_multi' => 'admin_players_multi',
	'fields_create' => array(
		'Wymagane' => array(
			'name' => array(
				'label' => 'Imię i nazwisko',
				'description' => 'Imię i nazwisko zawodnika',
				'type' => 'text',
				'validators' => 'required|max:127|unique:players,name',
				'escape' => true,
			),
			'number' => array(
				'label' => 'Numer',
				'description' => 'Numer zawodnika',
				'type' => 'text',
				'validators' => 'required|integer|max:255',
				'escape' => true,
			),
			'position' => array(
				'label' => 'Pozycja',
				'description' => 'Pozycja na której zwykle ten użytkownik występuje',
				'type' => 'text',
				'validators' => 'required|max:127',
				'escape' => true,
			),
			'team_id' => array(
				'label' => 'Klub',
				'description' => 'Klub zawodnika',
				'type' => 'related',
				'validators' => 'required|exists:teams,id',
				'related_table' => 'teams',
				'related_key' => 'id',
				'related_value' => 'name',
			),
		),
		'Inne' => array(
			'image' => array(
				'label' => 'Zdjęcie',
				'description' => 'Zdjęcia zawodnika',
				'type' => 'upload',
				'validators' => 'image',
				'upload_dir' => 'players',
				'remove' => true
			),
			'date' => array(
				'label' => 'Data urodzin',
				'description' => 'Data urodzin zawodnika',
				'type' => 'text',
				'validators' => 'match:!^[0-9]{4}-[0-9]{2}-[0-9]{2}$!',
			),
			'height' => array(
				'label' => 'Wysokość',
				'description' => 'Wysokość zawodnika w centymetrach',
				'type' => 'text',
				'validators' => 'integer',
				'int' => true
			),
			'weight' => array(
				'label' => 'Waga',
				'description' => 'Waga zawodnika w kilogramach',
				'type' => 'text',
				'validators' => 'integer',
				'int' => true
			),
			'cost' => array(
				'label' => 'Koszt',
				'description' => 'Za jakie pieniądze przyszedł do obecnego klubu. Dowolna waluta',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'prev_club' => array(
				'label' => 'Poprzedni klub',
				'description' => 'Poprzedni klub, w którym ten zawodnik występował',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'birthplace' => array(
				'label' => 'Miejsce urodzin',
				'description' => 'Gdzie ten zawodnik się urodził',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'country' => array(
				'label' => 'Kraj',
				'description' => 'Z jakiego kraju ten zawodnik pochodzi',
				'type' => 'text',
				'validators' => 'max:10',
				'escape' => true,
			),
			'is_on_loan' => array(
				'label' => 'Wypożyczenie',
				'description' => 'Czy ten zawodnik jest obecnie wypożyczony z innego klubu',
				'type' => 'checkbox',
				'validators' => '',
			),
			'description' => array(
				'label' => 'Opis',
				'description' => 'Informacje o zawodniku',
				'type' => 'editor',
				'validators' => '',
			),
		),
	),
	'fields_edit' => array(
		'Wymagane' => array(
			'name' => array(
				'label' => 'Imię i nazwisko',
				'description' => 'Imię i nazwisko zawodnika',
				'type' => 'text',
				'validators' => 'required|max:127|unique:players,name,(:id)',
				'escape' => true,
			),
			'slug' => array(
				'label' => 'Slug',
				'description' => 'Slug widoczny w linkach do podstrony',
				'type' => 'text',
				'validators' => 'required|max:127|alpha_dash|unique:players,slug,(:id)',
				'escape' => true,
			),
			'number' => array(
				'label' => 'Numer',
				'description' => 'Numer zawodnika',
				'type' => 'text',
				'validators' => 'required|integer|max:255',
				'escape' => true,
			),
			'position' => array(
				'label' => 'Pozycja',
				'description' => 'Pozycja na której zwykle ten użytkownik występuje',
				'type' => 'text',
				'validators' => 'required|max:127',
				'escape' => true,
			),
			'team_id' => array(
				'label' => 'Klub',
				'description' => 'Klub zawodnika',
				'type' => 'related',
				'validators' => 'required|exists:teams,id',
				'related_table' => 'teams',
				'related_key' => 'id',
				'related_value' => 'name',
			),
		),
		'Inne' => array(
			'image' => array(
				'label' => 'Zdjęcie',
				'description' => 'Zdjęcia zawodnika',
				'type' => 'upload',
				'validators' => 'image',
				'upload_dir' => 'players',
				'remove' => true
			),
			'date' => array(
				'label' => 'Data urodzin',
				'description' => 'Data urodzin zawodnika',
				'type' => 'text',
				'validators' => 'match:!^[0-9]{4}-[0-9]{2}-[0-9]{2}$!',
			),
			'height' => array(
				'label' => 'Wysokość',
				'description' => 'Wysokość zawodnika w centymetrach',
				'type' => 'text',
				'validators' => 'integer',
				'int' => true
			),
			'weight' => array(
				'label' => 'Waga',
				'description' => 'Waga zawodnika w kilogramach',
				'type' => 'text',
				'validators' => 'integer',
				'int' => true
			),
			'cost' => array(
				'label' => 'Koszt',
				'description' => 'Za jakie pieniądze przyszedł do obecnego klubu. Dowolna waluta',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'prev_club' => array(
				'label' => 'Poprzedni klub',
				'description' => 'Poprzedni klub, w którym ten zawodnik występował',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'birthplace' => array(
				'label' => 'Miejsce urodzin',
				'description' => 'Gdzie ten zawodnik się urodził',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'country' => array(
				'label' => 'Kraj',
				'description' => 'Z jakiego kraju ten zawodnik pochodzi',
				'type' => 'text',
				'validators' => 'max:10',
				'escape' => true,
			),
			'is_on_loan' => array(
				'label' => 'Wypożyczenie',
				'description' => 'Czy ten zawodnik jest obecnie wypożyczony z innego klubu',
				'type' => 'checkbox',
				'validators' => '',
			),
			'description' => array(
				'label' => 'Opis',
				'description' => 'Informacje o zawodniku',
				'type' => 'editor',
				'validators' => '',
			),
		),
	),
);