<?php
return array(
	'delete' => true,
	'delete_log' => 'Usunięto klub: %s',
	'delete_log_sub' => 'name',
	'add_log' => 'Dodano klub: %s',
	'add_log_sub' => 'name',
	'edit_log' => 'Zmieniono klub: %s',
	'edit_log_sub' => 'name',
	'table' => 'teams',
	'edit' => true,
	'create' => true,
	'acl_delete' => 'admin_teams_delete',
	'acl_edit' => 'admin_teams_edit',
	'acl_add' => 'admin_teams_add',
	'title' => 'Kluby',
	'title_edit' => 'Edycja klubu',
	'title_add' => 'Dodawanie klubu',
	'slug' => 'slug',
	'slug_from' => 'name',
	'grid' => true,
	'acl_grid' => 'admin_teams',
	'acl_grid_multi' => 'admin_teams_multi',
	'fields_create' => array(
		'Wymagane' => array(
			'name' => array(
				'label' => 'Nazwa',
				'description' => 'Nazwa klubu',
				'type' => 'text',
				'validators' => 'required|max:127|unique:teams,name',
				'escape' => true,
			),
			'image' => array(
				'label' => 'Herb',
				'description' => 'Herb klubu',
				'type' => 'upload',
				'validators' => 'required|image',
				'upload_dir' => 'teams'
			),
			'is_distinct' => array(
				'label' => 'Wyróżniony',
				'description' => 'Wyróżnić klub w tabelach itp.',
				'type' => 'checkbox',
				'validators' => '',
			),
		),
		'Inne' => array(
			'year' => array(
				'label' => 'Rok założenia',
				'description' => 'Rok założenia klubu',
				'type' => 'text',
				'validators' => 'integer|min:1800|max:2100',
				'int' => true
			),
			'address' => array(
				'label' => 'Adres',
				'description' => 'Adres klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'colors' => array(
				'label' => 'Barwy',
				'description' => 'Barwy klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'stadium' => array(
				'label' => 'Stadion',
				'description' => 'Stadion klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'chairman' => array(
				'label' => 'Prezes',
				'description' => 'Prezes/prezydent klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'coach' => array(
				'label' => 'Trener',
				'description' => 'Trener/menedżer klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'star' => array(
				'label' => 'Gwiazda',
				'description' => 'Gwiazda zespołu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'webpage' => array(
				'label' => 'Strona internetowa',
				'description' => 'Link do strony internetowej klubu',
				'type' => 'text',
				'validators' => 'max:127|url',
				'escape' => true,
			),
			'description' => array(
				'label' => 'Opis',
				'description' => 'Informacje o klubie',
				'type' => 'editor',
				'validators' => '',
			),
		),
	),
	'fields_edit' => array(
		'Wymagane' => array(
			'name' => array(
				'label' => 'Nazwa',
				'description' => 'Nazwa klubu',
				'type' => 'text',
				'validators' => 'required|max:127|unique:teams,name',
				'escape' => true,
			),
			'slug' => array(
				'label' => 'Slug',
				'description' => 'Slug widoczny w linkach',
				'type' => 'text',
				'validators' => 'required|max:127|alpha_dash|unique:teams,slug,(:id)',
				'escape' => true,
			),
			'image' => array(
				'label' => 'Herb',
				'description' => 'Herb klubu',
				'type' => 'upload',
				'validators' => 'image',
				'upload_dir' => 'teams'
			),
			'is_distinct' => array(
				'label' => 'Wyróżniony',
				'description' => 'Wyróżnić klub w tabelach itp.',
				'type' => 'checkbox',
				'validators' => '',
			),
		),
		'Inne' => array(
			'year' => array(
				'label' => 'Rok założenia',
				'description' => 'Rok założenia klubu',
				'type' => 'text',
				'validators' => 'integer|min:1800|max:2100',
				'int' => true
			),
			'address' => array(
				'label' => 'Adres',
				'description' => 'Adres klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'colors' => array(
				'label' => 'Barwy',
				'description' => 'Barwy klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'stadium' => array(
				'label' => 'Stadion',
				'description' => 'Stadion klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'chairman' => array(
				'label' => 'Prezes',
				'description' => 'Prezes/prezydent klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'coach' => array(
				'label' => 'Trener',
				'description' => 'Trener/menedżer klubu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'star' => array(
				'label' => 'Gwiazda',
				'description' => 'Gwiazda zespołu',
				'type' => 'text',
				'validators' => 'max:127',
				'escape' => true,
			),
			'webpage' => array(
				'label' => 'Strona internetowa',
				'description' => 'Link do strony internetowej klubu',
				'type' => 'text',
				'validators' => 'max:127|url',
				'escape' => true,
			),
			'description' => array(
				'label' => 'Opis',
				'description' => 'Informacje o klubie',
				'type' => 'editor',
				'validators' => '',
			),
		),
	),
);