<?php
return array(
	'delete' => true,
	'delete_log' => 'Usunięto obiekt: %s',
	'delete_log_sub' => 'title',
	'add_log' => 'Dodano obiekt: %s',
	'add_log_sub' => 'title',
	'edit_log' => 'Zmieniono obiekt: %s',
	'edit_log_sub' => 'title',
	'table' => 'reports',
	'edit' => true,
	'create' => true,
	'acl_delete' => 'admin_test_delete',
	'acl_edit' => 'admin_test_edit',
	'acl_add' => 'admin_test_add',
	'title' => 'Reporty',
	'title_edit' => 'Edycja reportu',
	'title_add' => 'Dodawanie reportu',
	'slug' => 'slug',
	'slug_from' => 'title',
	'grid' => true,
	'acl_grid' => 'admin_test',
	'acl_grid_multi' => 'admin_test_multi',
	'fields_create' => array(
		'Sekcja' => array(
			'name' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'text',
				'validators' => 'required',
				'escape' => true,
			),
			'textarea' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'textarea',
				'validators' => 'required',
			),
			'editor' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'editor',
				'validators' => 'required',
			),
			'password' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'password',
				'validators' => 'required',
			),
			'checkbox' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'checkbox',
				'validators' => 'required',
			),
			'image2' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'upload',
				'validators' => 'required',
				'upload_dir' => 'test2',
			),
			'name2' => array(
				'label' => 'Tytuł 2',
				'description' => 'Opis pola 2',
				'type' => 'related',
				'validators' => 'required|exists:widgets,id',
				'related_table' => 'widgets',
				'related_key' => 'id',
				'related_value' => 'title',
			),
			'name3' => array(
				'label' => 'Tytuł 3',
				'description' => 'Opis pola 3',
				'type' => 'select',
				'validators' => 'required|in:test,test2',
				'options' => array('test' => 'Test', 'test2' => 'Test2')
			),
		),
	),
	'fields_edit' => array(
		'Sekcja' => array(
			'name' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'text',
				'validators' => 'required',
			),
			'textarea' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'textarea',
				'validators' => 'required',
			),
			'editor' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'editor',
				'validators' => 'required',
			),
			'image2' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'upload',
				'validators' => 'required',
				'upload_dir' => 'test2',
				'upload_remove' => true,
			),
			'password' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'password',
				'validators' => 'required',
			),
			'checkbox' => array(
				'label' => 'Tytuł',
				'description' => 'Opis pola',
				'type' => 'checkbox',
				'validators' => 'required',
			),
			'name2' => array(
				'label' => 'Tytuł 2',
				'description' => 'Opis pola 2',
				'type' => 'related',
				'validators' => 'required|exists:widgets,id,(:id)',
				'related_table' => 'widgets',
				'related_key' => 'id',
				'related_value' => 'title',
			),
			'name3' => array(
				'label' => 'Tytuł 3',
				'description' => 'Opis pola 3',
				'type' => 'select',
				'validators' => 'required|in:test,test2',
				'options' => array('test' => 'Test', 'test2' => 'Test2')
			),
		),
	),
);